website/calculate_calories/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from calculate_calories import views

admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^home/$', views.home , name = "home"),
    url(r'^register/$', views.register, name = 'register'),
    url(r'^login/$', views.login , name = "login"),
    url(r'^logout/$', views.logout , name = "logout"),
    url(r'^profile/$', views.profile , name = "profile"),
    url(r'^track_calories/$', views.track_calories , name = "track_calories"),
    url(r'^about/$', views.about , name = "about"),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', views.home, name = "home"),
)

website/website/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

admin.autodiscover()


urlpatterns = patterns(
    '',
    url(r'^', include('calculate_calories.urls')),
    url(r'^admin/$', include(admin.site.urls)),
)

website/calculate_calories/models.py
from datetime import datetime

from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth.models import User, UserManager


class UserProfile(models.Model):
    FEMALE = 'f'
    MALE = 'm'
    GENDER = (
        (FEMALE, 'female'),
        (MALE, 'male')
    )
    SPORTS = (
        (1.2, "Does not do sport."),
        (1.375, "Does sport 1 to 3 times weekly."),
        (1.55, "Does sport 3 to 5 times weekly."),
        (1.725, "Does sport 6 to 7 times weekly."),
        (1.9, "Extreme active: 7 times weekly with additional activities.")
    )
    user = models.OneToOneField(User)
    gender = models.CharField(max_length=1,
                              choices=GENDER,
                              default=FEMALE)
    age = models.PositiveIntegerField(null=True)
    kilograms = models.PositiveIntegerField(null=True)
    height = models.PositiveIntegerField(null=True)
    sports = models.FloatField(choices=SPORTS, default = SPORTS[0][0])
    calorie_balance = models.PositiveIntegerField(default=0)
    date_joined = models.DateTimeField(default=datetime.now(),
                                       auto_now_add=True,
                                       null=True)
    objects = UserManager()

    def __str__(self):
        return self.user.username

    def save(self, *args, **kwargs):
        try:
            existing = UserProfile.objects.get(user=self.user)
            self.id = existing.id  # force update instead of insert
        except UserProfile.DoesNotExist:
            pass
        models.Model.save(self, *args, **kwargs)


def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)

post_save.connect(create_user_profile, sender=User)


class Food(models.Model):
    name = models.TextField(blank=False)
    foodtype = models.TextField(blank=False)
    #  calories in 100 gr food
    calories_per_100gr = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.name

    class Meta:
        unique_together = (('name', 'foodtype'),)


class Consumation(models.Model):
    user = models.ForeignKey(UserProfile, related_name='consumation')
    food = models.ForeignKey(Food, related_name='consumation')
    amount_of_food = models.PositiveIntegerField(default=0)
    date = models.DateTimeField(auto_now_add=True)
    calories_consumated = models.PositiveIntegerField(default=0)

    def __str__(self):
        return "{} - {} calories in {} grams.".format(self.food_id, self.calories_consumated, self.amount_of_food)


class Temp(models.Model):
    food1 = models.TextField(default='')
    food2 = models.TextField(default='')
    food1_amount = models.PositiveIntegerField(blank=False, default=0)
    food2_amount = models.PositiveIntegerField(blank=False, default=0)
    date = models.DateTimeField(default=datetime.now(),
                                auto_now_add=True,
                                null=True)

    def __str__(self):
        return str(self.food1) + " - " + str(self.food1_amount) + " and " + str(self.food2) + " - " + str(self.food2_amount)

    class Meta:
        unique_together= (('food1', 'food2', 'food1_amount', 'food2_amount'),)

website/calculate_calories/forms.py
import re

from django import forms
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _

from .models import UserProfile, Food, Consumation, Temp
from .formfields import ChoiceField


class UserRegistrationForm(forms.Form):
    username = forms.CharField(label=_('Username'), max_length=50)
    email = forms.EmailField(label=_("Email address"))
    password = forms.CharField(
        widget=forms.PasswordInput(attrs=dict(
        required=True,
        max_length=30,
        render_value=False)),
        label=_("Password"))
    password_confirm = forms.CharField(
        widget=forms.PasswordInput(attrs=dict(
        required=True,
        max_length=30,
        render_value=False)),
        label=_("Password (again)")
        )
    first_name = forms.CharField(max_length=30)
    last_name = forms.CharField(max_length=30)

    def clean_username(self):
        username = self.cleaned_data.get('username')
        try:
            user = User.objects.get(username__iexact=username)
        except User.DoesNotExist:
            return username
        raise forms.ValidationError(_("The username already exists. Please try another one."))

    def clean(self):
        password = self.cleaned_data.get('password')
        password_confirm = self.cleaned_data.get('password_confirm')
        if password != password_confirm:
            raise forms.ValidationError(_("The two password fields did not match."))
        return self.cleaned_data

    class Meta:
        model = User


class UserProfileRegistrationForm(forms.Form):
    GENDER = (
        ('f', 'female'),
        ('m', 'male')
    )
    SPORTS = (
        (1.2, "Does not do sport."),
        (1.375, "Does sport 1 to 3 times weekly."),
        (1.55, "Does sport 3 to 5 times weekly."),
        (1.725, "Does sport 6 to 7 times weekly."),
        (1.9, "Extreme active: 7 times weekly with additional activities.")
    )
    gender = forms.ChoiceField(required=True, choices=GENDER)
    kilograms = forms.IntegerField(required=True)
    age = forms.IntegerField(required=True)
    height = forms.IntegerField(required=True)
    sports = forms.FloatField(required=True)

    def save(self, *args, **kw):
        super(UserProfileRegistrationForm, self).save(*args, **kw)
        self.instance.user.first_name = self.cleaned_data.get('first_name')
        self.instance.user.last_name = self.cleaned_data.get('last_name')
        self.instance.user.gender = self.cleaned_data.get('gender')
        self.instance.user.kilograms = self.cleaned_data.get('kilograms')
        self.instance.user.height = self.cleaned_data.get('height')
        self.instance.user.sports = self.cleaned_data.get('sports')
        self.instance.user.age = self.cleaned_data.get('age')
        self.instance.user.save()

    class Meta:
        model = UserProfile


class LoginForm(forms.Form):
    username = forms.RegexField(
        regex=r'^\w+$',
        label=_("Username"),
        widget=forms.TextInput(
            attrs=dict(required=True, max_length=30,)
            ),
        error_messages={'invalid':
                      _("This value must contain only letters, numbers and underscores.")}
        )
    password = forms.CharField(widget=forms.PasswordInput(attrs=dict(
                               required=True,
                               max_length=30,
                               render_value=False)),
                               label=_("Password"))


class CaloriesForm(forms.Form):
    food_name = forms.ModelMultipleChoiceField(queryset=Food.objects.all())
    amount_of_food = forms.IntegerField(required=True)


class WhatToEatForm(forms.Form):
    food = forms.ModelMultipleChoiceField(
        queryset=Food.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        )
    amount = forms.IntegerField(required=True)
    another_food = forms.ModelMultipleChoiceField(
        queryset=Food.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        )
    another_amount = forms.IntegerField(required=True)

    class Meta:
        model = Temp

website/calculate_calories/views.py
from datetime import datetime

from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect, render_to_response
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.views.decorators.csrf import csrf_protect
from django.http import HttpResponseRedirect
from django.template import RequestContext
from django.contrib.auth import authenticate, login as django_login, logout as django_logout
from django.db import IntegrityError

from calculate_calories.models import Temp, UserProfile, Food, Consumation
from calculate_calories.forms import UserProfileRegistrationForm, UserRegistrationForm, WhatToEatForm, LoginForm, CaloriesForm
from calculate_calories.helper import add_food_in_db, get_2_combinations, calories, combine


def home(request):
   return render(request, 'home.html')


def about(request):
   return render(request, 'about.html')


@csrf_protect
def register(request):
    if not request.user.is_authenticated():
        if request.method == 'POST':
            uform = UserRegistrationForm(data=request.POST)
            pform = UserProfileRegistrationForm(data=request.POST)
            if uform.is_valid() and pform.is_valid():
                balance = calories(
                 pform.cleaned_data['gender'],
                 pform.cleaned_data['kilograms'],
                 pform.cleaned_data['height'],
                 pform.cleaned_data['age'],
                 pform.cleaned_data['sports'])

                new_user = User.objects.create_user(
                    username=uform.cleaned_data['username'],
                    password=uform.cleaned_data['password1'],
                    email=uform.cleaned_data['email'],
                    first_name=uform.cleaned_data['first_name'],
                    last_name=uform.cleaned_data['last_name'])
                user_profile = UserProfile(
                    user=new_user,
                    gender=pform.cleaned_data['gender'],
                    age=pform.cleaned_data['age'],
                    kilograms=pform.cleaned_data['kilograms'],
                    height=pform.cleaned_data['height'],
                    sports=pform.cleaned_data['sports'],
                    calorie_balance=balance)
                user_profile.save()
                return HttpResponseRedirect('/home/')
        else:
            uform = UserRegistrationForm()
            pform = UserProfileRegistrationForm()
        variables = RequestContext(request, {
                                'uform': uform,
                                'pform': pform
        })
        return render_to_response('register.html', variables)
    else:
        return HttpResponseRedirect('profile')


def track_calories(request):
    if request.user.is_authenticated():
        user_profile = UserProfile.objects.get(user=request.user)
        foods = Consumation.objects.filter(user_id=user_profile)

        combinations = Temp.objects.all()
        if len(combinations) > 0:
            Temp.objects.all().delete()

        cal = user_profile.calorie_balance

        food_today = []
        for food in foods:
            if datetime.today().date() == food.date.date():
                food_today.append(food)
                cal -= food.calories_consumated

    if request.method == 'POST':
        sform = WhatToEatForm(data=request.POST)
        form = CaloriesForm(data=request.POST)
        if form.is_valid():
            food = form.cleaned_data['food_name']
            food_calories = food.first().calories_per_100gr
            calories = form.cleaned_data['amount_of_food'] / 100 * food_calories
            user_food = Consumation(
            user_id=user_profile,
            food_id=food.first(),
            amount_of_food=form.cleaned_data['amount_of_food'],
            calories_consumated=calories
            )
            user_food.save()
            return HttpResponseRedirect('/track_calories/')

        if sform.is_valid():
            food_to_combine = sform.cleaned_data['food']
            another_food_to_combine = sform.cleaned_data['another_food']
            amount = sform.cleaned_data['amount']
            another_amount = sform.cleaned_data['another_amount']

            for combination in combinations:
                if food_to_combine.first().food_name == combination.food1 and another_food_to_combine.first().food_name == combination.food2:
                    attempt = get_2_combinations(food_to_combine.first().food_type, food_to_combine.first().calories_per_100gr, amount, another_food_to_combine.first().food_type, another_food_to_combine.first().calories_per_100gr, another_amount, cal)
            else:
                attempt = get_2_combinations(food_to_combine.first().food_type, food_to_combine.first().calories_per_100gr, amount, another_food_to_combine.first().food_type, another_food_to_combine.first().calories_per_100gr, another_amount, cal)

            if len(attempt) < 2 and len(attempt) > 0:
                food_try = Temp(
                    food1=food_to_combine.first().food_name,
                    food1_amount=attempt[0][1],
                    )
                food_try.save()
            elif attempt:
                for i in range(0, len(attempt)-1):
                    try:
                        food_try = Temp(
                            food1=food_to_combine.first().food_name,
                            food2=another_food_to_combine.first().food_name,
                            food1_amount=attempt[i][i+1],
                            food2_amount=attempt[i+1][i+1]
                            )
                    except IndexError as e:
                        return HttpResponseRedirect('/track_calories/')

                    try:
                        food_try.save()
                    except IntegrityError as e:
                        return HttpResponseRedirect('/track_calories/')

            return HttpResponseRedirect('/track_calories/')
    else:
        sform = WhatToEatForm()
        form = CaloriesForm()
    variables = RequestContext(request, {
    'form': form,
    'sform': sform,
    })
    return render_to_response("track_calories.html", locals(), variables)


def login(request):
    if request.method == 'POST':
        form = LoginForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=form.cleaned_data['username'], password=form.cleaned_data['password'])
            if user is not None:
                if user.is_active:
                    django_login(request, user)
                else:
                    print("The password is valid, but the account has been disabled!")
            else:
                print("The username and password were incorrect.")
            return HttpResponseRedirect('/home/')
    else:
        form = LoginForm()
    return render(request, 'login.html', {'form': form})


@login_required
def profile(request):
    if request.user.is_authenticated():
        user_profile = UserProfile.objects.get(user=request.user)
    return render(request, 'profile.html', locals())


@login_required
def logout(request):
    django_logout(request)
    return redirect('/login/')

website/calculate_calories/templates/about.html
{% extends 'base.html' %}

{% block content %}

<p>
This site is created to help people be fit. The main idea is that we can all get fitter and in form only by consuming the needed calories for our body and no more.

</p>
<p>
For your comfort the site have the functunallity calculate the calories you need for a day so that you stay in form and your body gets what it needs.
</p>
<p>
Nevertheless we have a big database of food so you can choose what you eat today and how much of it and we will calculate the calories for you and subtract them from the calories of the day.
</p>

{% endblock %}

website/calculate_calories/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="../../assets/ico/favicon.ico">

    <title>Live healthier today</title>

    <!-- Bootstrap core CSS -->
    <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="jumbotron.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy this line! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="navbar-header">
          <a href = '{% url "home" %}'>
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Home</span>
            </button>
            </a>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>

          {% if user.is_authenticated%}
            <a href='{% url "track_calories" %}'>
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only"> Calories for today</span>
          </button>
          </a>
            <a href='{% url "profile" %}'>
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only"> {{ user.username}} Profile</span>
          </button>
          </a>
          {% else %}
           <a href = '{% url "register" %}'>
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Register</span>
            </button>
            </a>
          {% endif %}
          <a href='{% url "about" %}'>
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">About us</span>
          </button>
          </a>
          <hr>
        </div>

    <div class="jumbotron">
      <div class="container">
      <br>
      {% if user.is_authenticated %}
            <div>You are currently logged in as {{ user.username }}</div>
            <a href='{% url "logout" %}'>
            <button type="button"  class="nav navbar-nav navbar-right">
            <span class="sr-only">Log out</span>
          </button>
          </a>
      {% else %}
        <!--  <div class="navbar-collapse collapse">
          <form class="navbar-form navbar-right" role="form">
            {% csrf_token %}
            {{ form.as_p}}
            <div class="form-group">
              <input type="text" placeholder="Email" class="form-control">
            </div>
            <div class="form-group">
              <input type="password" placeholder="Password" class="form-control">
            </div>
            <button type="submit" class="btn btn-success">Sign in</<button></button>n>
          </form>
        </div><!-/.navbar-collapse -->
      <!-- </div> -->
    <!-- </div> -->
     <a href='{% url "login" %}'>
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Login</span>
          </button>
          </a>
      {% endif %}
        <br>
        <br>
        <h1>Welcome to live healthy.</h1>
      {% block content %}
        <p>We want to make it as easier as possible for you to live as healthy as you wish
        to. Please do register yourself with valid data so our calculation.</p>
        <p><a class="btn btn-primary btn-lg" role="button">Learn more &raquo;</a></p>
      </div>
    </div>

    <div class="container">
      <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-4">
          <h2>Heading</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div>
      </div>
      {% endblock %}

      <hr>

      <footer>
        <p>&copy; Snezhana Spasova</p>
      </footer>
    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
  </body>
</html>

website/calculate_calories/templates/home.html
{% extends 'base.html' %}

website/calculate_calories/templates/login.html
{% extends 'base.html' %}

{% block content %}

<form action="/login/" method="post">

    {% csrf_token %}
    {{ form.as_p }}

<button type="submit" class="btn btn-success">Sign in</button>

</form>

{% endblock %}

website/calculate_calories/templates/logout.html
{% extends 'base.html' %}

website/calculate_calories/templates/profile.html
{% extends 'base.html' %}

{% block content %}

<p> Hello, {{ user.first_name }} {{ user.last_name }}!</p>

<p> Your calories maximum is {{ user_profile.calorie_balance }}. </p>
<p> Your age is {{ user_profile.age }}. </p>


<!-- <a href = '/update_profile/'>
  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
    <span class="sr-only">Update profile</span>
    </button>
    </a> -->

{% endblock %}

website/calculate_calories/templates/register.html
{% extends 'base.html' %}
{% block content %}
<form action="/register/" method="post">
    {% csrf_token %}
<!--     {{ uform.as_p }}
    {{ pform.as_p }}  -->
    {{ form.non_field_errors }}
    <div class="fieldWrapper">
        <label for="id_email">Email:</label>
        {{ uform.email }}

    </div>
    <div class="fieldWrapper">
        {{ form.password1.errors }}
        <label for="id_username" >Password:</label>
        {{ uform.password1 }}

        </div>
    <div class="fieldWrapper">
        {{ form.password2.errors }}
        <label for="id_username" >Confirm password:</label>
        {{ uform.password2 }}
        
    <div class="fieldWrapper">
        {{ uform.username.errors }}
        <label for="id_username" >Username:</label>
        {{ uform.username }}

    </div>
    <div class="fieldWrapper">
        {{ form.sender.errors }}
        <label for="id_first_name">First name:</label>
        {{ uform.first_name }}

    </div>
    <div class="fieldWrapper">
        <label for="id_last_name">Last name:</label>
       {{ uform.last_name }}

    </div>
    <div class="fieldWrapper">
        <label for="id_gender">Gender:</label>
        {{ pform.gender }}

    <div class="fieldWrapper">
        <label for="id_last_name">Age:</label>
       {{ pform.age }}

    </div>
    <div class="fieldWrapper">
        <label for="id_kilograms">Kilograms</label>
        {{ pform.kilograms }}

    </div>
    <div class="fieldWrapper">
        <label for="id_height">Height</label>
        {{ pform.height }}

    </div>
    <div class="fieldWrapper">
        <label for="id_sports">Sport:</label>
        <select id="id_sports" name="sports">
        <option value='1.2'>Does not do sport.</option>
        <option value="1.375">Does sport 1 to 3 times weekly.</option>
        <option value='1.55'>Does sport 3 to 5 times weekly.</option>
        <option value='1.725'>Does sport 6 to 7 times weekly.</option>
        <option value='1.9'>Extreme active: 7 times weekly with additional activities.</option>
        </select>
    <p><input type="submit" value="Register" /></p>
</form> 
{% endblock %}

website/calculate_calories/templates/track_calories.html
{% extends 'base.html' %}

{% block content %}

<p> Hello, {{ user.first_name }} {{ user.last_name }}!</p>

<p> Your calorie maximum is {{ user_profile.calorie_balance }}. </p>
<p> Today you consumated: </p>

{% for food in food_today %}

    </br>

    {{ food }}

{% endfor %}

{% if cal > 0 %}

<p> You have {{ cal }} calories left.</p>

{% else %}

<p> You've reached your calories maximum and have {{ cal }} calories over the line.</p>

{% endif %}


<p> Add more:</p>

<form action="/track_calories/" method="post">

{% csrf_token %}
{{ form.as_p }}

</br>

<input type="submit" />
</form>

<hr>
{% if cal > 0 %}
<p>Need help with figuring out what to eat?</p>

<form action="/track_calories/" method="post">

{% csrf_token %}
{{ sform.as_p}}

<input type="submit" />
</form>

{% if combinations %}
<p>You can consumate:</p>
{% for combination in combinations %}

    </br>
    {{ combination }}

{% endfor %}

{% endif %}

{% else %}
<p> You have already reached your maximum.</p>

{% endif %}

{% endblock %}